# Generated by Django 4.2.13 on 2024-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='techstack',
            fields=[
                ('class_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('refrence', models.CharField(max_length=2)),
            ],
        ),
    ]
